[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "sh -c \"gunicorn --bind 0.0.0.0:$PORT --workers=2 --threads=2 --timeout 600 --graceful-timeout 600 webapp.app:app\""
healthcheckPath = "/health"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.multiRegionConfig]
  [deploy.multiRegionConfig.us-east4]
  numReplicas = 1
