[build]
builder = "DOCKER"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers=2 --threads=2 webapp.app:app"
healthcheckPath = "/health"
sleepApplication = false
multiRegionConfig = {"us-east4":{"numReplicas":1}}
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10